apiVersion: k3d.io/v1alpha5  # K3d configuration API version
kind: Simple  # Defines a simple K3d cluster configuration
metadata:
  name: my-iot-cluster  # Name of the K3d cluster

servers: 1  # Number of server (control plane) nodes

image: rancher/k3s:latest  # Specifies the K3s image to use (latest version)

ports:
  # Maps port 80 inside the cluster (load balancer) to port 8082 on the host machine
  - port: 8082:80  
    nodeFilters:
      - loadbalancer  # Applies this port mapping to the load balancer node

  # Maps the Kubernetes NodePort range (30000-32767) from the server node to the host
  - port: 30000-32767:30000-32767  
    nodeFilters:
      - server:0  # Applies this rule to the first server node (control plane)
