apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: my-iot-cluster
servers: 1
image: rancher/k3s:latest
ports:
  - port: 8082:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer