---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset-app
  labels:
    name: my-replicaset
    type: test-replicaset
spec:
  template:
    metadata:
      name: my-pod-app
      labels:
        app: my-pod-app
        type: test-pod
    spec:
      containers:
      - name: nginx-app
        image: nginx
  replicas: 9
  selector:
    matchLabels:
      type: test-pod
