apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-k3d-cluster-p3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/a-boudoun/Inception_of_things/
    targetRevision: fechcha_part2_k3s_apps_setup
    # targetRevision: HEAD
    path: confs/k3s_manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
