apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
    type: app1

spec:
  template:
    metadata:
      name: app1-pod
      labels:
        name: app1-pod
        type: app1-pod
    spec:
      containers:
      - name: app1-container
        image: amiss/app1:v1
        ports:
        - containerPort: 3000
  replicas: 1
  selector:
    matchLabels:
      type: app1-pod


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: app2
    type: app2

spec:
  template:
    metadata:
      name: app2-pod
      labels:
        name: app2-pod
        type: app2-pod
    spec:
      containers:
      - name: app2-container
        image: amiss/app2:v1
        ports:
        - containerPort: 3000
  replicas: 3
  selector:
    matchLabels:
      type: app2-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3
    type: app3

spec:
  template:
    metadata:
      name: app3-pod
      labels:
        name: app3-pod
        type: app3-pod
    spec:
      containers:
      - name: app3-container
        image: amiss/app3:v1
        ports:
        - containerPort: 3000
  replicas: 1
  selector:
    matchLabels:
      type: app3-pod
