apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: deploy-app1
    type: deploy-app1
spec:
  template:
    metadata:
      name: app1-pod
      labels:
        app: portfolio
        type: pod-app1
    spec:
      containers:
        - name: portfolio1-pod
          image: fechcha69/fechcha-portfolio-app1
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio
      type: pod-app1


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    app: deploy-app2
    type: deploy-app2
spec:
  template:
    metadata:
      name: app2-pod
      labels:
        app: portfolio
        type: pod-app2
    spec:
      containers:
        - name: portfolio2-pod
          image: fechcha69/fechcha-portfolio-app2
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio
      type: pod-app2


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: deploy-app3
    type: deploy-app3
spec:
  template:
    metadata:
      name: app3-pod
      labels:
        app: portfolio
        type: pod-app3
    spec:
      containers:
        - name: portfolio3-pod
          image: fechcha69/fechcha-portfolio-app3
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio
      type: pod-app3


---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app1
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001


---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app2
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002

  
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app3
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
spec:
  rules:
  - host: "app1.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-service
            port:
              number: 5000
  - host: "app2.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-service
            port:
              number: 5000
  - host: "app3.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app3-service
            port:
              number: 5000

