apiVersion: v1
kind: Service
metadata:
  name: app1-service

spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app1
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001


---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app2
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002

  
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  type: NodePort
  selector:
    app: portfolio
    type: pod-app3
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30003