apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: deploy-app1
    type: deploy-app1
spec:
  template:
    metadata:
      name: app1-pod
      labels:
        app: portfolio
        type: pod-app1
    spec:
      containers:
        - name: portfolio1-pod
          image: fechcha69/fechcha-portfolio-app1
          ports:
          - containerPort: 6969
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portfolio
      type: pod-app1