apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-app
  labels:
    app: deploy-app
    type: deploy-test
spec:
  template:
    metadata:
      name: my-pod-app
      labels:
        app: pod-app
        type: pod-test
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.7.1
  replicas: 4
  selector:
    matchLabels:
      type: pod-test
      